language: scala
jdk:
  - oraclejdk8
scala:
  - 2.11.7
script:
  - "./buildViaTravis.sh"
env:
  global:
    secure: "b1dhsDzfhOzZAlETu38P5yRdHCdPIJ6yzIs9H/zTuwEHTrCSUNxuRIdUIN11CJkXkdzVOkRqirdKv1oCWT7AMt4VsaYKo83+dDeOMSSz3YGXKq7MJz++/1gfOGxEsXqd2u0gC9qpC1S/cl+T9S11Rm7SLpOf+uJegoVKrbWHbbHuv878DWWmGm0a9fmD3VrTdQ8aRWYJ28zCGsozSDrmlY75X8r7zHIEK/RDUdIHtcylmG4wStbn7eS3yKI4AUigcx0O0xzquZIInXaIn6WF/my0JjSIpLe8TasvWZQM9T8KfTc0X0+Iah8phs+uQZnJGWK21odPOGoKY7NtpCljFIl+PdHMi8SGodCzooGV7ltZMlNebolYbw5EY762nWRLTb5mC7NgDxDDuy4rG43s7I3X/3iUgJTudHKCwgHdKnNfual8uLcv/hM7M0tOY3XxP59LzBggiFW9kkOoYvdiS1DqNfMA9lYAmDaqipvwsLKOowdtikYAGFRSM67nnqKUyo6yJa+G/TyCTKaNjq8YNu5dUA7P3U36IsetX8bJ7/3aeCw5q/fJ63cQeCbqNDh2sHQda/niRm2cLl38jDOOGB5BSd6oMzC9wyOVud/xecGkeqBRVVPcRp7qqYJBUK2ddT1Yg8OVfTN2Y8Omf9lppCa8YUawAc2ielAnuomGbRE="
    secure: "dIEr7EU4gnAaeLeD0erQsLyGXhl+SUvkBkxhXlzIRq5c6uflXc1SxC+vQMIDQirt1RDDzOn+ac173PchDixO2dXvtNOUwRfX7uyGTpDL6o9PixrbG8Pzymr8O+1z0Htwk4jgnkApWNajiRpY0gQePGlJhux9+voD0/qk8D1DPWUPtL+Q8lHeaJLLhodm4pqIAtiHP3VP8oaxs0ll7/jqgnRj62U7CSM8s+wRPf8To1rFTKnSUSLD6xhT7+XJzVvfGfD5wtARbFnTFrslXC4cggWCJvzQco4JPY94xFDWD4mUrdPrAx3bSKsmXUMrPBC9KyS+dwUyaOLP3q5SZR/P8otlse6JqAiVkwUGhEJ0Qh/wCrXRBFvBTshZ/TTOTGywqdjNQ0DutDHSptBUFRJJez1HRdrhjIs4O19BlzajIAN4BWucVQeR3KVi0VCajfxCo95AjkrAU+BTNhDDA9dxKj0LTtCp6XeM2RME+TB2I8aKCnhz7Gtb1BxWhpSnDFi7jX/6qadzyUinP/3xnL+HmNNw3p90NiNm3PqAQepDWcz2QnP6CbxpynJVs08Mcrem9i3FwpqDYAbR1E7HtxuG2MBLwbZEyIRtVgSH3IJ95B2XeXL6CkymU4dn7vO2gspcJa/lAbTJFeTKVWjrj0GrorOX0x05gx6w5zvrPx3JT0w="
cache:
  directories:
  - $HOME/.sbt
  - $HOME/.ivy2
